apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: kustomization-eks-repository
  newName: 499176689708.dkr.ecr.us-east-1.amazonaws.com/msa-order
  newTag: DEV_demoapp-service_0a1128d5
